/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Object returned to JS */
export interface ParsedTx {
  signer: string
  mint: string
  curve: string
  ownerVault: string
  otherValue: string
}
export declare function signMessage(message: Buffer, secretKey: Buffer): string
/**
 * JS export: `associatedTokenAddress(...)`
 *   mint_buf          - 32-byte Buffer (mint public key)
 *   token_program_buf - 32-byte Buffer (spl-token or token-2022 program id)
 *   owner_buf         - 32-byte Buffer (wallet pubkey)
 * Returns             - 32-byte Buffer (ATA pubkey)
 *
 * The token program is an argument because every current pump.fun launch (`create_v2`)
 * mints a token-2022 mint, whose ATA is derived under a different program id.
 */
export declare function associatedTokenAddress(mintBuf: Buffer, tokenProgramBuf: Buffer, ownerBuf: Buffer): Buffer
/**
 * JS export: `findProgramAddress(...)`
 *   seed_buf     – arbitrary seed bytes (e.g. your `staticSeed`)
 *   mint_buf     – 32-byte Buffer
 *   program_id   – base58 string
 * Returns        – 32-byte Buffer  (PDA pubkey)
 */
export declare function findProgramAddress(seedBuf: Buffer, mintBuf: Buffer, programId: string): Buffer
/**
 * entry_b64         – the tx as base-64
 * init_sol          – initialVirtualSolReserves  (decimal string)
 * init_token        – initialVirtualTokenReserves(decimal string)
 */
export declare function parseBuyTx(entryB64: string, initSol: string, initToken: string): ParsedTx
